package gr.opa.booking.common.enums;

public enum MessageType {
    REGISTER_WORKER,
    SAVE_ROOM,
    BOOKING_STATISTICS,
    MASTER_SEARCH,
    WORKER_SEARCH,
    REDUCER_RESULTS,
    SEARCH_RESULTS,
    CLIENT_IDENTIFICATION,
    CLIENT_RESULTS,
    BOOKING_ROOM,
    BOOKING_SUCCESS,
    BOOKING_FAILURE,
    WORKER_BOOKING_ROOM,
    RATE_ROOM,
    WORKER_STATISTICS,
    REDUCER_STATISTICS,
    STATISTICS_RESULTS,
    CLIENT_EXIT,
    WORKER_ALIVE,
    ADD_ROOM,
    ROOMS_RESERVATIONS,
    WORKER_RESERVATIONS,
    REDUCER_RESERVATIONS,
    RESERVATIONS_RESULTS
}
